_commit: 0.1.6
_src_path: gh:kj-9/click-app-copier
app_name: click app copier template demo
author_name: kj-9
description: Demonstrating https://github.com/kj-9/click-app-copier
github_username: kj-9
update: true
