_commit: 30073a5
_src_path: main
app_name: click app copier template demo
author_name: kj-9
description: Demonstrating https://github.com/kj-9/click-app-copier
github_username: kj-9
hyphenated: click-app-copier-template-demo
underscored: click_app_copier_template_demo
